# Generated by Django 2.0.5 on 2018-05-05 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('face_hash', models.TextField()),
            ],
            options={
                'verbose_name': 'attendee',
                'verbose_name_plural': 'attendees',
            },
        ),
        migrations.CreateModel(
            name='ContentEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
            ],
            options={
                'verbose_name': 'content event',
                'verbose_name_plural': 'content events',
            },
        ),
        migrations.CreateModel(
            name='DataEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('up', 'Up'), ('dn', 'Down')], max_length=2, verbose_name='event type')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Attendee')),
            ],
            options={
                'verbose_name': 'data event',
                'verbose_name_plural': 'data events',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
            ],
            options={
                'verbose_name': 'performance',
                'verbose_name_plural': 'performances',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
            ],
            options={
                'verbose_name': 'stages',
                'verbose_name_plural': 'stages',
            },
        ),
        migrations.AddField(
            model_name='performance',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Stage'),
        ),
        migrations.AddField(
            model_name='dataevent',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Stage'),
        ),
        migrations.AddField(
            model_name='contentevent',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Performance'),
        ),
    ]
