# Generated by Django 2.0.5 on 2018-05-06 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180505_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetlistEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='start time')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Performance')),
            ],
            options={
                'verbose_name': 'setlist entry',
                'verbose_name_plural': 'setlist entries',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100, verbose_name='artist')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('cover', models.URLField(blank=True, verbose_name='cover')),
            ],
        ),
        migrations.AlterField(
            model_name='dataevent',
            name='event_type',
            field=models.CharField(choices=[('up', '👍'), ('dn', '👎')], max_length=2, verbose_name='event type'),
        ),
        migrations.AddField(
            model_name='setlistentry',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Song'),
        ),
        migrations.AddField(
            model_name='performance',
            name='setlist',
            field=models.ManyToManyField(through='api.SetlistEntry', to='api.Song'),
        ),
    ]
