# Generated by Django 2.0.5 on 2018-05-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180506_0802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setlistentry',
            options={'ordering': ('start_time',), 'verbose_name': 'setlist entry', 'verbose_name_plural': 'setlist entries'},
        ),
        migrations.AlterField(
            model_name='setlistentry',
            name='start_time',
            field=models.DateTimeField(verbose_name='start time'),
        ),
    ]
