# Generated by Django 2.0.5 on 2018-05-06 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180506_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentevent',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='dataevent',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='setlistentry',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='start time'),
        ),
    ]
