# Generated by Django 2.0.5 on 2018-05-06 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180506_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('up', '👍'), ('dn', '👎')], max_length=2, verbose_name='event type')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Attendee')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Performance')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Song')),
            ],
        ),
        migrations.AddField(
            model_name='dataevent',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='processed'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='playlist',
            field=models.ManyToManyField(through='api.PlaylistEntry', to='api.Song'),
        ),
    ]
