# Generated by Django 2.0.5 on 2018-05-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180506_1110'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendee',
            unique_together={('user_id', 'face_hash')},
        ),
    ]
