# Generated by Django 2.0.5 on 2018-05-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180506_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='user_id',
            field=models.UUIDField(unique=True),
        ),
    ]
